name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    strategy:
      matrix: 
        include:
          - image: code-server
            context: code-server
          - image: jupyter-all-spark
            context: jupyter-all-spark
    name: Build and Push ${{ matrix.image }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            image:
              - '${{ matrix.image }}/**'
    
      - name: Login to Docker Hub
        if: steps.changes.outputs.image == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and Push
        if: steps.changes.outputs.image == 'true'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
          context: ${{ matrix.context }}
